server:
  port: 8085

spring:
  application:
    name: admin-server

eureka:
  client:
    register-with-eureka: true  # Ставим true, чтобы сервис регистрировался в Eureka
    fetch-registry: true         # Убираем false, чтобы сервис мог получать информацию о других сервисах
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Указываем URL Eureka сервера
      instance:
        prefer-ip-address: true



loki4j:
  http:
    connectTimeoutMs: 300000
    readTimeoutMs: 300000


management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  prometheus:
    metrics:
      export:
        enabled: true
