services:
  harbor-db:
    image: goharbor/harbor-db:v2.3.0
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /mnt/data/harbor-db:/var/lib/postgresql/data
    networks:
      - harbor

  harbor-core:
    image: goharbor/harbor-core:v2.3.0
    environment:
      - CORE_SECRET=secret
    networks:
      - harbor

  harbor-jobservice:
    image: goharbor/harbor-jobservice:v2.3.0
    networks:
      - harbor

  harbor-registry:
    image: goharbor/harbor-registry:v2.3.0
    networks:
      - harbor

  nginx:
    image: goharbor/nginx-photon:v2.3.0
    ports:
      - "8080:8080"
    networks:
      - harbor

networks:
  harbor:
    driver: bridge
