version: '3.8'

services:
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - product-db
    networks:
      - monitoring

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - product-db
    networks:
      - monitoring

  product-db:
    image: postgres:16
    container_name: product-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    networks:
      - monitoring
    volumes:
      - pg_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "C:/Users/Пользователь/Desktop/Main-Projects/SportMagazine/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:

volumes:
  grafana_data:
  pg_data: