scrape_configs:
  - job_name: svanchukov_admin_service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8085"]

remote_write:
  - url: "http://host.docker.internal:8428/api/v1/write"