version: "3.9"

services:
  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - product-net

  product-service:
    build: .   # путь до Dockerfile
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: product
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - product-db
    networks:
      - product-net

volumes:
  pgdata:

networks:
  product-net:
    driver: bridge
