#FROM eclipse-temurin:21-jdk AS build
#WORKDIR /app
#
#COPY product-service/pom.xml .
#RUN mvn dependency:go-offline -B
#
#COPY product-service/src ./src
#
#RUN mvn clean package -DskipTests
#
#FROM eclipse-temurin:21-jre
#WORKDIR -app
#COPY --from=build /app/target/