global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Это для самого Prometheus
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']