apiVersion: v1
kind: Service
metadata:
  name: product-service  # Заменили _ на -
spec:
  selector:
    app: product-service  # Заменили _ на -
  ports:
    - protocol: TCP
      port: 8080  # Порт сервиса
      targetPort: 8080  # Порт контейнера
  type: LoadBalancer  # Для доступа извне в Minikube