server:
  port: 8765

spring:
  main:
    web-application-type: reactive

  autoconfigure:
    exclude:

  security:
    jwt:
      secret: Wv0yHc2Z9UrP7kDxLE1JV5yQnQxSe5L7pEwTyg0A9dE=
      expiration: 3600000

  debug: true

  cloud:
    gateway:
      routes:

#        - id: user-swagger
#          uri: http://localhost:8083
#          predicates:
#            - Path=/swagger-ui/**
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/(?<segment>.*),/${segment}
#
#        - id: gateway-auth
#          uri: no://op
#          predicates:
#            - Path=/auth/**
#
#        - id: user-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/users/**
#          filters:
#            - RewritePath=/users/(?<segment>.*),/${segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /swagger/api-docs
