server:
  port: 8087

spring:
  application:
    name: gateway-service
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8080/products
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:8081/order-api/products
          predicates:
            - Path=/order/**
        - id: user-service
          uri: http://localhost:8082/users
          predicates:
            - Path=/user/**
