server:
  port: 8765

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8083
          predicates:
            - Path=/auth/login
          filters:
            - RewritePath=/auth/login, /users/login

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/swagger-ui/*
          filters:
            - JwtFilter
            - RewritePath=/users/(?<segment>.*), /${segment}

        - id: user-swagger
          uri: http://localhost:8083
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**
          filters:
            - JwtFilter
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

jwt:
  secret: "0654417d70c4e760579abfb090b6336d5044862389821d766ce5a9f4713c12c5"
  expiration: 3600000
