server:
  port: 8083

spring:

  application:
    name: User-Service

  datasource:
    url: jdbc:postgresql://localhost:5433/user
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # опционально

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  logging:
    level:
      org.springframework: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

