server:
  port: 8083

spring:

  application:
    name: User-Service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    url: ${URL_DATASOURCE_DB:jdbc:postgresql://localhost:5433/user}
    username: ${NAME_POSTGRES:user}
    password: ${PASSWORD_POSTGRES:user}
    driver-class-name: ${DRIVER_NAME:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${POOL_SIZE:10}  # опционально

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    clear-checksums: true
    change-log: classpath:db/scripts_liquibase/v.1.0.0/0000-init-table.xml
    enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${URL_EUREKA:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

