server:
  port: 8083

spring:

  security:
    jwt:
      secret: 0654417d70c4e760579abfb090b6336d5044862389821d766ce5a9f4713c12c5
      expiration-ms: 3600000

  datasource:
    url: ${URL_DATASOURCE_DB:jdbc:postgresql://localhost:5433/user}
    username: ${NAME_POSTGRES:user}
    password: ${PASSWORD_POSTGRES:user}
    driver-class-name: ${DRIVER_NAME:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${POOL_SIZE:10}  # опционально
      connection-timeout: 30000
  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true

  liquibase:
    clear-checksums: true
    change-log: classpath:db/scripts_liquibase/v.1.0.0/0000-init-table.xml
    enabled: true


  application:
    name: user-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${URL_EUREKA:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

