server:
  port: 8081

spring:
  application:
    name: order-service
  messages:
    basename: messages
    encoding: UTF-8

  #  boot:
#    admin:
#      client:
#        enabled: true
#        instance:
#          service-host-type: ip
#        url: http://localhost:8085

  datasource:
      url: ${URL_DATASOURCE_DB:jdbc:postgresql://localhost:5434/products}
      username: ${NAME_POSTGRES:products}
      password: ${PASSWORD_POSTGRES:products}
      driver-class-name: ${DRIVER_NAME:org.postgresql.Driver}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/scripts_liquibase/v.1.0.0/0000-init-table.xml
    enabled: true

eureka:
  client:
    register-with-eureka: true  # Ставим true, чтобы сервис регистрировался в Eureka
    fetch-registry: true         # Убираем false, чтобы сервис мог получать информацию о других сервисах
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true


management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
