create table products (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(128) not null ,
                          category varchar(128) not null ,
                          descriptions TEXT ,
                          price DECIMAL(10,2) not null,
                          brand varchar(128) not null
);


ALTER TABLE products ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE products ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;



