svanchukov:
  services:
    order:
      uri: http://localhost:8080

spring:
  datasource:
    url: ${URL_DATASOURCE_DB:jdbc:postgresql://localhost:5432/products}
    username: ${NAME_POSTGRES:products}
    password: ${PASSWORD_POSTGRES:products}
    driver-class-name: ${DRIVER_NAME:org.postgresql.Driver}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      org.springframework: DEBUG
      com.zaxxer.hikari: DEBUG

  application:
    name: product-service

  liquibase:
    change-log: classpath:db/scripts_liquibase/v.1.0.0/0000-init-table.xml
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

