svanchukov:
  services:
    order:
      uri: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
    driver-class-name: org.postgresql.Driver

  application:
    name: product-service  # Исправлена ошибка в формате



  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true  # Эта настройка уже правильная

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Прокидываем нужные эндпоинты для мониторинга

  prometheus:
    metrics:
      export:
        enabled: true  # Включаем экспорт метрик для Prometheus

eureka:
   client:
     register-with-eureka: true  # Ставим true, чтобы сервис регистрировался в Eureka
     fetch-registry: true         # Убираем false, чтобы сервис мог получать информацию о других сервисах
     service-url:
       defaultZone: http://localhost:8761/eureka/  # Указываем URL Eureka сервера
       instance:
         prefer-ip-address: true
