apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # Имя, указанное в SPRING_DATASOURCE_URL
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # Порт PostgreSQL
      targetPort: 5432
  type: ClusterIP  # Доступ только внутри кластера