version: "3.9"

services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - user-net

  user-service:
    build: .   # путь до Dockerfile
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8082:8080"
    depends_on:
      - user-db
    networks:
      - user-net

volumes:
  pgdata:

networks:
  user-net:
    driver: bridge
